### PR TITLE
Ac 154 account settings issue

### PR DESCRIPTION
**Pull request by wacefEssaies96**

### CODE REVIEW

**Comment by LianArthofer** [comment]
save function not working, it is not saving the data @wacefEssaies96

**Comment by wacefEssaies96** [comment]
the save button is fixed, now when we press save, the data will be saved in firebase

**Comment by LianArthofer** [comment]
please fix failing tests @wacefEssaies96

**Comment by wacefEssaies96** [comment]
tests fixed

**Review by LianArthofer — APPROVED** [review]

**Pull request merged**
